//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtDayEmber
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Preferences = new HashSet<Preference>();
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int id { get; set; }
        public int grade { get; set; }
        public Nullable<bool> locked { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
